In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [173]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


In [174]:
fin_phrase_TF_IDF_df = pd.read_csv('../Data/Prepared/fin_phrase_TF_IDF.csv')
fin_phrase_TF_IDF_df

Unnamed: 0  Count
0            ab     28
1           abb      3
2       ability      3
3          able     17
4           abn      3
...         ...    ...
3846    youtube      2
3847        yty      2
3848        zao      2
3849       zinc      7
3850       zone      7

[3851 rows x 2 columns]

In [175]:
fin_phrase_TF_IDF_df = fin_phrase_TF_IDF_df.rename(columns={'Unnamed: 0': 'Words'})
fin_phrase_TF_IDF_df

Words  Count
0          ab     28
1         abb      3
2     ability      3
3        able     17
4         abn      3
...       ...    ...
3846  youtube      2
3847      yty      2
3848      zao      2
3849     zinc      7
3850     zone      7

[3851 rows x 2 columns]

In [176]:
# Assuming tfidf_df contains your TF-IDF features and target contains your target variable
# X contains the TF-IDF features, y contains the target variable
X = fin_phrase_TF_IDF_df
y = fin_phrase_TF_IDF_df['Count']  # Assuming 'target' is the name of the target variable


In [177]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)



In [178]:
y_test

2754     13
457       2
291     127
3624      2
3064      7
       ... 
1151      3
2708     35
1053     22
3196    154
22       24
Name: Count, Length: 1156, dtype: int64

In [179]:
# Initialize the Logistic Regression model
model = LogisticRegression()


In [180]:
y_train.shape

(2695,)

In [181]:
X_train_reshaped = X_train['Count'].values.reshape(-1, 1)

In [182]:
# Train the model on the training data
model.fit(X_train_reshaped, y_train)


/home/juann/anaconda3/envs/DDB/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [183]:
X_test_reshaped = X_test['Count'].values.reshape(-1, 1)
X_test_reshaped

array([[ 13],
       [  2],
       [127],
       ...,
       [ 22],
       [154],
       [ 24]])

In [184]:
# Predict the target variable on the testing data
y_pred = model.predict(X_test_reshaped)
y_pred


array([ 7,  2, 49, ..., 10, 49, 10])

In [185]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.5449826989619377


In [186]:
# Assuming y_test and y_pred are already defined
report = classification_report(y_test, y_pred, output_dict=True)

# Convert the report dictionary to a DataFrame
report_df = pd.DataFrame(report).transpose()

# Optionally, you can reset the index to have the labels as a column
report_df.reset_index(inplace=True)
report_df.rename(columns={'index': 'class'}, inplace=True)

print(report_df)

           class  precision    recall  f1-score      support
0              2   1.000000  1.000000  1.000000   365.000000
1              3   1.000000  1.000000  1.000000   157.000000
2              4   0.613636  1.000000  0.760563   108.000000
3              5   0.000000  0.000000  0.000000    68.000000
4              6   0.000000  0.000000  0.000000    62.000000
..           ...        ...       ...       ...          ...
88           872   0.000000  0.000000  0.000000     1.000000
89           904   0.000000  0.000000  0.000000     0.000000
90      accuracy   0.544983  0.544983  0.544983     0.544983
91     macro avg   0.029040  0.033333  0.030673  1156.000000
92  weighted avg   0.508886  0.544983  0.522613  1156.000000

[93 rows x 5 columns]


/home/juann/anaconda3/envs/DDB/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/juann/anaconda3/envs/DDB/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/juann/anaconda3/envs/DDB/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/juann/

In [187]:
report_df.to_csv("../Data/Prepared/fin_report_df.csv")

In [188]:
np.unique(y_test)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  50,  51,  52,  53,  54,  55,
        56,  58,  62,  67,  68,  73,  74,  75,  78,  80,  81,  83,  85,
        87,  89,  90,  91, 101, 103, 111, 112, 127, 128, 136, 138, 139,
       154, 262, 294, 311, 333, 384, 410, 473, 544, 872])

In [189]:
len(np.unique(y_test))

88